version: '3.8'

services:
  postgres:
    image: 'postgres:latest'
    container_name: postgres-db
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: secret
    ports:
      - '5432:5432'
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4
    container_name: my-pgadmin
    ports:
      - '82:80'
    environment:
      PGADMIN_DEFAULT_EMAIL: test@gmail.com
      PGADMIN_DEFAULT_PASSWORD: sifre123
    restart: unless-stopped
    depends_on:
      - postgres
