name: Java CI/CD Workflow

on:
  pull_request: # Pull Request sırasında tetiklenir
    branches:
      - master
      - dev-selcuk
      - dev-numan

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # 1. Kodu klonla
      - name: Checkout Code
        uses: actions/checkout@v3

      # 2. Java ortamını kur
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'

      # 3. Maven bağımlılıklarını önbelleğe al
      - name: Cache Maven Dependencies
        uses: actions/cache@v4.2.0
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      # 4. Maven bağımlılıklarını indir
      - name: Install Dependencies
        run: mvn install -DskipTests

      # 5. Testleri çalıştır
      - name: Run Tests
        run: mvn test

      # 6. Derlemeyi kontrol et
      - name: Verify Build
        run: mvn compile
