name: Java CI/CD Workflow

on:
  push:
    branches:
      - dev-selcuk  # dev-selcuk branch'ine push olduğunda çalıştır
      - dev-numan   # dev-numan branch'ine push olduğunda çalıştır
      - master      # master branch'ine push olduğunda çalıştır
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Kodu GitHub deposundan klonla
      - name: Checkout Code
        uses: actions/checkout@v3

      # 2. Java ortamını kur
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'

      # 3. Maven bağımlılıklarını indir
      - name: Install Dependencies
        run: mvn install -DskipTests

      # 4. Maven testlerini çalıştır
      - name: Run Tests
        run: mvn test

      # 5. Uygulamayı derle
      - name: Build Project
        run: mvn package -DskipTests

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'

      # 6. Branch'e göre farklı bir deploy işlemi ekle
      - name: Conditional Deploy
        if: github.ref_name == 'master'
        run: echo "Master branch için deploy işlemi başlatılıyor."

      - name: Conditional Deploy for dev-selcuk
        if: github.ref_name == 'dev-selcuk'
        run: echo "dev-selcuk branch için özel işlemler başlatılıyor."

      - name: Conditional Deploy for dev-numan
        if: github.ref_name == 'dev-numan'
        run: echo "dev-numan branch için özel işlemler başlatılıyor."
